export const QUESTIONS = [
  {
    questionnaireNo: 1,
    question:
      "You've been assigned a challenging project at work that requires working closely with a diverse team. Each team member brings unique perspectives and work styles to the table. As you navigate through this project, which of the following qualities do you prioritize the most in yourself? Please rank the options according to your preferences, with 1 being the most preferred and 5 being the least preferred.",
    question_category: "default",
    questionOptionType: "RANKING",
    questionWeightageType: "Ranking_Competency",
    optionsList: [
      "Recognizing strengths and weaknesses enhances team contribution and interpersonal impact.",
      "Maintaining composure aids in handling pressure, fostering a productive work environment.",
      "Embracing setbacks inspires resilience and determination, fostering growth.",
      "Understanding team perspectives enhances collaboration and communication.",
    ],
    selectedOption: null,
    selectedOrder: [
      "Recognizing strengths and weaknesses enhances team contribution and interpersonal impact.",
      "Maintaining composure aids in handling pressure, fostering a productive work environment.",
      "Embracing setbacks inspires resilience and determination, fostering growth.",
      "Understanding team perspectives enhances collaboration and communication.",
    ],
    saveText: "Save Order",
    section: 1,
    mostLikely: "",
    leastLikely: "",
  },
  {
    questionnaireNo: 2,
    question:
      "You've been assigned to lead a cross-functional team on a critical project. As the project progresses, you notice some tensions arising among team members. How would you prioritize your approach to address this situation? Please rank the options according to your preferences, with 1 being the most preferred and 5 being the least preferred.",
    question_category: "default",
    questionOptionType: "RANKING",
    questionWeightageType: "Ranking_Competency",
    optionsList: [
      "Sharing personal anecdotes to find common ground.",
      "Maintaining eye contact and refraining from distractions.",
      "Acknowledging their perspective and suggesting compromise.",
      "Being transparent about your capabilities and limitations.",
    ],
    selectedOption: null,
    selectedOrder: [
      "Sharing personal anecdotes to find common ground.",
      "Maintaining eye contact and refraining from distractions.",
      "Acknowledging their perspective and suggesting compromise.",
      "Being transparent about your capabilities and limitations.",
    ],
    saveText: "Save Order",
    section: 1,
    mostLikely: "",
    leastLikely: "",
  },
  {
    questionnaireNo: 3,
    question:
      "Imagine you've been tasked with leading a team to revamp an outdated company process. The current method is causing inefficiencies and hindering progress. Your team needs to implement a solution swiftly. Rank the following approaches according to your preferences",
    question_category: "default",
    questionOptionType: "RANKING",
    questionWeightageType: "Ranking_Competency",
    optionsList: [
      "Embracing change readily and being open to modifying plans as new information arises, ensuring flexibility and quick adjustments to overcome challenges.",
      "Identifying the root cause of inefficiencies and devising practical, effective solutions to address them, focusing on resolving issues efficiently and effectively.",
      "Making well-informed and timely decisions based on available data and analysis, ensuring that actions taken are strategic and aligned with the overall goals of the project.",
      "Prioritizes tasks based on urgency and importance, creating a detailed timeline to allocate time efficiently and ensure timely completion of deliverables.",
    ],
    selectedOption: null,
    selectedOrder: [
      "Embracing change readily and being open to modifying plans as new information arises, ensuring flexibility and quick adjustments to overcome challenges.",
      "Identifying the root cause of inefficiencies and devising practical, effective solutions to address them, focusing on resolving issues efficiently and effectively.",
      "Making well-informed and timely decisions based on available data and analysis, ensuring that actions taken are strategic and aligned with the overall goals of the project.",
      "Prioritizes tasks based on urgency and importance, creating a detailed timeline to allocate time efficiently and ensure timely completion of deliverables.",
    ],
    saveText: "Save Order",
    section: 1,
    mostLikely: "",
    leastLikely: "",
  },
  {
    questionnaireNo: 4,
    question:
      "Your company is seeking to enhance its customer service experience, and you need an ideal candidate to lead this transformation. What attributes would you prioritize in this candidate?  Rank the traits you would prioritize from most to least in an ideal candidate?",
    question_category: "default",
    questionOptionType: "RANKING",
    questionWeightageType: "Ranking_Pillar",
    optionsList: [
      "A candidate with strong relationship-building skills, capable of cultivating long-lasting connections with customers.",
      "Someone who excels in problem-solving, quickly resolving customer issues and finding innovative solutions. ",
      "An individual who demonstrates empathy, understanding the needs and concerns of customers and providing personalized support.",
      "An individual who empowers team members by providing opportunities for growth and development, fostering a culture of mentorship and support. ",
      "A candidate with a proven track record of mastering complex technical challenges, demonstrating exceptional problem-solving skills.",
    ],
    selectedOption: null,
    selectedOrder: [
      "A candidate with strong relationship-building skills, capable of cultivating long-lasting connections with customers.",
      "Someone who excels in problem-solving, quickly resolving customer issues and finding innovative solutions. ",
      "An individual who demonstrates empathy, understanding the needs and concerns of customers and providing personalized support.",
      "An individual who empowers team members by providing opportunities for growth and development, fostering a culture of mentorship and support. ",
      "A candidate with a proven track record of mastering complex technical challenges, demonstrating exceptional problem-solving skills.",
    ],
    saveText: "Save Order",
    section: 1,
    mostLikely: "",
    leastLikely: "",
  },
  {
    questionnaireNo: 5,
    question:
      "How do you typically manage stress in a high-pressure work environment?",
    question_category: "default",
    questionOptionType: "RATING",
    questionWeightageType: "Rating",
    optionsList: [
      "Organized task management fosters progress and accomplishment.",
      "Proactively addressing stress maintains well-being and effectiveness.",
      "Reflective practices aid in navigating challenges with clarity and composure.",
    ],
    selectedOption: null,
    selectedOrder: [
      "Organized task management fosters progress and accomplishment.",
      "Proactively addressing stress maintains well-being and effectiveness.",
      "Reflective practices aid in navigating challenges with clarity and composure.",
    ],
    saveText: "Save Order",
    section: 1,
    mostLikely: "",
    leastLikely: "",
  },
  {
    questionnaireNo: 6,
    question:
      "When facing a sudden increase in workload, how do you ensure your stress levels remain manageable?",
    question_category: "default",
    questionOptionType: "RATING",
    questionWeightageType: "Rating",
    optionsList: [
      "Open communication ensures balanced workloads and successful outcomes.",
      "Dedication to goals balances with self-care for sustainable effectiveness.",
      "Proactive task management ensures consistent progress and success.",
    ],
    selectedOption: null,
    selectedOrder: [
      "Open communication ensures balanced workloads and successful outcomes.",
      "Dedication to goals balances with self-care for sustainable effectiveness.",
      "Proactive task management ensures consistent progress and success.",
    ],
    saveText: "Save Order",
    section: 1,
    mostLikely: "",
    leastLikely: "",
  },
  {
    questionnaireNo: 7,
    question:
      "In times of uncertainty or ambiguity, how do you maintain a sense of calm and focus?",
    question_category: "default",
    questionOptionType: "RATING",
    questionWeightageType: "Rating",
    optionsList: [
      "Prioritizing self-care cultivates resilience and positive mindset.",
      "Confidence in overcoming setbacks inspires perseverance and growth.",
      "Solutions-oriented approach navigates challenges with positivity and collaboration.",
    ],
    selectedOption: null,
    selectedOrder: [
      "Prioritizing self-care cultivates resilience and positive mindset.",
      "Confidence in overcoming setbacks inspires perseverance and growth.",
      "Solutions-oriented approach navigates challenges with positivity and collaboration.",
    ],
    saveText: "Save Order",
    section: 1,
    mostLikely: "",
    leastLikely: "",
  },
  {
    questionnaireNo: 8,
    question:
      "Your company is undergoing a restructuring, leading to uncertainty and anxiety among employees. How would you cope with the stress of organizational changes?",
    question_category: "default",
    questionOptionType: "RATING",
    questionWeightageType: "Rating",
    optionsList: [
      "Processing feedback fosters growth and self-improvement.",
      "Fostering psychological safety encourages expression and learning.",
      "Offering support cultivates resilience and progress.",
    ],
    selectedOption: null,
    selectedOrder: [
      "Processing feedback fosters growth and self-improvement.",
      "Fostering psychological safety encourages expression and learning.",
      "Offering support cultivates resilience and progress.",
    ],
    saveText: "Save Order",
    section: 1,
    mostLikely: "",
    leastLikely: "",
  },
  {
    questionnaireNo: 9,
    question:
      "You have a heavy workload and tight deadlines approaching. What specific time management technique would you use to prioritize tasks?",
    question_category: "default",
    questionOptionType: "RATING",
    questionWeightageType: "Rating",
    optionsList: [
      "Balanced decision-making ensures effective outcomes.",
      "Acknowledging emotions facilitates growth and learning.",
      "Celebrating successes fosters motivation and camaraderie.",
    ],
    selectedOption: null,
    selectedOrder: [
      "Balanced decision-making ensures effective outcomes.",
      "Acknowledging emotions facilitates growth and learning.",
      "Celebrating successes fosters motivation and camaraderie.",
    ],
    saveText: "Save Order",
    section: 1,
    mostLikely: "",
    leastLikely: "",
  },
  {
    questionnaireNo: 10,
    question:
      "You're feeling overwhelmed with work and personal commitments. What specific relaxation technique would you use to manage stress?",
    question_category: "default",
    questionOptionType: "RATING",
    questionWeightageType: "Rating",
    optionsList: [
      "Effective communication fosters understanding and teamwork.",
      "Embracing teamwork enhances overall performance.",
      "Building positive connections fosters a supportive environment.",
    ],
    selectedOption: null,
    selectedOrder: [
      "Effective communication fosters understanding and teamwork.",
      "Embracing teamwork enhances overall performance.",
      "Building positive connections fosters a supportive environment.",
    ],
    saveText: "Save Order",
    section: 1,
    mostLikely: "",
    leastLikely: "",
  },
  {
    questionnaireNo: 11,
    question:
      "In a high-pressure work environment, how do you typically respond to setbacks?",
    question_category: "default",
    questionOptionType: "RATING",
    questionWeightageType: "Rating",
    optionsList: [
      "Resolving conflicts constructively promotes growth and understanding.",
      "Recognizing and addressing inefficiencies drives effective solutions.",
      "Making well-informed decisions aligns with project goals.",
    ],
    selectedOption: null,
    selectedOrder: [
      "Resolving conflicts constructively promotes growth and understanding.",
      "Recognizing and addressing inefficiencies drives effective solutions.",
      "Making well-informed decisions aligns with project goals.",
    ],
    saveText: "Save Order",
    section: 1,
    mostLikely: "",
    leastLikely: "",
  },
  {
    questionnaireNo: 12,
    question:
      "How do you maintain your motivation and enthusiasm during challenging times?",
    question_category: "default",
    questionOptionType: "RATING",
    questionWeightageType: "Rating",
    optionsList: [
      "Prioritizing tasks ensures timely completion and goal alignment.",
      "Considering feedback and objectives guides decision-making.",
      "Evaluating risks and benefits informs strategic decisions.",
    ],
    selectedOption: null,
    selectedOrder: [
      "Prioritizing tasks ensures timely completion and goal alignment.",
      "Considering feedback and objectives guides decision-making.",
      "Evaluating risks and benefits informs strategic decisions.",
    ],
    saveText: "Save Order",
    section: 1,
    mostLikely: "",
    leastLikely: "",
  },
  {
    questionnaireNo: 13,
    question: "How do you approach setbacks in your personal life?",
    question_category: "default",
    questionOptionType: "RATING",
    questionWeightageType: "Rating",
    optionsList: [
      "Assessing cost-effectiveness guides resource allocation.",
      "Selecting software aligns with performance and usability needs.",
      "Handling bugs involves swift and transparent action.",
    ],
    selectedOption: null,
    selectedOrder: [
      "Assessing cost-effectiveness guides resource allocation.",
      "Selecting software aligns with performance and usability needs.",
      "Handling bugs involves swift and transparent action.",
    ],
    saveText: "Save Order",
    section: 1,
    mostLikely: "",
    leastLikely: "",
  },
  {
    questionnaireNo: 14,
    question:
      "Your project faces unexpected setbacks and delays. How would you demonstrate resilience in this situation?",
    question_category: "default",
    questionOptionType: "RATING",
    questionWeightageType: "Rating",
    optionsList: [
      "Addressing downtime involves investigation and resolution.",
      "Resolving quality issues involves root cause analysis and action.",
      "Profit margin is calculated based on percentage of revenue.",
    ],
    selectedOption: null,
    selectedOrder: [
      "Addressing downtime involves investigation and resolution.",
      "Resolving quality issues involves root cause analysis and action.",
      "Profit margin is calculated based on percentage of revenue.",
    ],
    saveText: "Save Order",
    section: 1,
    mostLikely: "",
    leastLikely: "",
  },
  {
    questionnaireNo: 15,
    question:
      "You receive negative feedback on a project you've been working on diligently. How would you bounce back from this setback?",
    question_category: "default",
    questionOptionType: "RATING",
    questionWeightageType: "Rating",
    optionsList: [
      "Project duration is determined based on weeks.",
      "Expense estimation is based on projected financial impact.",
      "Adapting strategies fosters flexibility and success.",
    ],
    selectedOption: null,
    selectedOrder: [
      "Project duration is determined based on weeks.",
      "Expense estimation is based on projected financial impact.",
      "Adapting strategies fosters flexibility and success.",
    ],
    saveText: "Save Order",
    section: 1,
    mostLikely: "",
    leastLikely: "",
  },
  {
    questionnaireNo: 16,
    question:
      "Your team experiences a major project failure. How would you lead your team through this challenging situation?",
    question_category: "default",
    questionOptionType: "RATING",
    questionWeightageType: "Rating",
    optionsList: [
      "Leveraging team strengths achieves collective goals.",
      "Exploring new tools enhances productivity and adaptability.",
      "Overcoming setbacks leads to growth and improvement.",
    ],
    selectedOption: null,
    selectedOrder: [
      "Leveraging team strengths achieves collective goals.",
      "Exploring new tools enhances productivity and adaptability.",
      "Overcoming setbacks leads to growth and improvement.",
    ],
    saveText: "Save Order",
    section: 1,
    mostLikely: "",
    leastLikely: "",
  },
  {
    questionnaireNo: 17,
    question:
      "When faced with a difficult situation, how do you typically respond?",
    question_category: "default",
    questionOptionType: "RATING",
    questionWeightageType: "Rating",
    optionsList: [
      "Embracing opportunities fosters skill development.",
      "Supporting organizational changes aids in transition success.",
      "Prioritizing tasks optimizes efficiency and effectiveness.",
    ],
    selectedOption: null,
    selectedOrder: [
      "Embracing opportunities fosters skill development.",
      "Supporting organizational changes aids in transition success.",
      "Prioritizing tasks optimizes efficiency and effectiveness.",
    ],
    saveText: "Save Order",
    section: 1,
    mostLikely: "",
    leastLikely: "",
  },
  {
    questionnaireNo: 18,
    question: "How do you handle constructive criticism from others?",
    question_category: "default",
    questionOptionType: "RATING",
    questionWeightageType: "Rating",
    optionsList: [
      "Taking breaks improves focus and productivity.",
      "Adapting to disruptions ensures project success.",
      "Managing tasks efficiently promotes timely completion.",
    ],
    selectedOption: null,
    selectedOrder: [
      "Taking breaks improves focus and productivity.",
      "Adapting to disruptions ensures project success.",
      "Managing tasks efficiently promotes timely completion.",
    ],
    saveText: "Save Order",
    section: 1,
    mostLikely: "",
    leastLikely: "",
  },
  {
    questionnaireNo: 19,
    question:
      "How do you prioritize tasks when you have multiple deadlines approaching?",
    question_category: "default",
    questionOptionType: "RATING",
    questionWeightageType: "Rating",
    optionsList: [
      "Communicating effectively facilitates project coordination.",
      "Maintaining high standards ensures quality outcomes.",
      "I prioritize tasks based on my interests, believing that enthusiasm leads to better results.",
    ],
    selectedOption: null,
    selectedOrder: [
      "Communicating effectively facilitates project coordination.",
      "Maintaining high standards ensures quality outcomes.",
      "I prioritize tasks based on my interests, believing that enthusiasm leads to better results.",
    ],
    saveText: "Save Order",
    section: 1,
    mostLikely: "",
    leastLikely: "",
  },
  {
    questionnaireNo: 20,
    question: "How do you handle conflicts in a team setting?",
    question_category: "default",
    questionOptionType: "RATING",
    questionWeightageType: "Rating",
    optionsList: [
      "I actively listen to all perspectives to find collaborative solutions that satisfy everyone.",
      "I assert my opinions firmly, believing in the importance of standing up for what I believe in.",
      "I set boundaries between work and personal time to ensure I allocate time for relaxation and hobbies.",
    ],
    selectedOption: null,
    selectedOrder: [
      "I actively listen to all perspectives to find collaborative solutions that satisfy everyone.",
      "I assert my opinions firmly, believing in the importance of standing up for what I believe in.",
      "I set boundaries between work and personal time to ensure I allocate time for relaxation and hobbies.",
    ],
    saveText: "Save Order",
    section: 1,
    mostLikely: "",
    leastLikely: "",
  },
  {
    questionnaireNo: 21,
    question: "How do you maintain a healthy work-life balance?",
    question_category: "default",
    questionOptionType: "RATING",
    questionWeightageType: "Rating",
    optionsList: [
      "I view setbacks as opportunities to learn and grow, using them as stepping stones toward success.",
      "I offer a listening ear and validate their feelings, providing support and understanding.",
      "I offer assistance and ask how I can help alleviate their burden.",
    ],
    selectedOption: null,
    selectedOrder: [
      "I view setbacks as opportunities to learn and grow, using them as stepping stones toward success.",
      "I offer a listening ear and validate their feelings, providing support and understanding.",
      "I offer assistance and ask how I can help alleviate their burden.",
    ],
    saveText: "Save Order",
    section: 1,
    mostLikely: "",
    leastLikely: "",
  },
  {
    questionnaireNo: 22,
    question: "How do you handle setbacks or failures?",
    question_category: "default",
    questionOptionType: "RATING",
    questionWeightageType: "Rating",
    optionsList: [
      "I take time to understand their perspective and discuss potential solutions collaboratively.",
      "I offer support and empathy, reassuring them that mistakes happen and it's a chance to learn.",
      "I express genuine happiness for their success, celebrating their achievements.",
    ],
    selectedOption: null,
    selectedOrder: [
      "I take time to understand their perspective and discuss potential solutions collaboratively.",
      "I offer support and empathy, reassuring them that mistakes happen and it's a chance to learn.",
      "I express genuine happiness for their success, celebrating their achievements.",
    ],
    saveText: "Save Order",
    section: 1,
    mostLikely: "",
    leastLikely: "",
  },
  {
    questionnaireNo: 23,
    question:
      "In a challenging situation, how do you typically respond to a friend who is feeling upset?",
    question_category: "default",
    questionOptionType: "RATING",
    questionWeightageType: "Rating",
    optionsList: [
      "Utilizing effective communication to convey ideas, share information, and foster understanding among team members.",
      "Embracing teamwork and cooperation to achieve shared goals.",
      "Investing in building positive connections and rapport with colleagues.",
    ],
    selectedOption: null,
    selectedOrder: [
      "Utilizing effective communication to convey ideas, share information, and foster understanding among team members.",
      "Embracing teamwork and cooperation to achieve shared goals.",
      "Investing in building positive connections and rapport with colleagues.",
    ],
    saveText: "Save Order",
    section: 1,
    mostLikely: "",
    leastLikely: "",
  },
  {
    questionnaireNo: 24,
    question:
      "You notice a colleague struggling with their workload. What's your approach?",
    question_category: "default",
    questionOptionType: "RATING",
    questionWeightageType: "Rating",
    optionsList: [
      "Skillfully navigating disagreements and resolving conflicts in a constructive manner.",
      "Arranging a one-on-one meeting with the team member to discuss their ideas privately.",
      "Politely interjecting and providing the missing detail to ensure the client receives accurate information.",
    ],
    selectedOption: null,
    selectedOrder: [
      "Skillfully navigating disagreements and resolving conflicts in a constructive manner.",
      "Arranging a one-on-one meeting with the team member to discuss their ideas privately.",
      "Politely interjecting and providing the missing detail to ensure the client receives accurate information.",
    ],
    saveText: "Save Order",
    section: 1,
    mostLikely: "",
    leastLikely: "",
  },
  {
    questionnaireNo: 25,
    question:
      "Your team member expresses concerns about a project's direction. What's your reaction?",
    question_category: "default",
    questionOptionType: "RATING",
    questionWeightageType: "Rating",
    optionsList: [
      "Holding a company-wide town hall meeting for interactive discussion and Q&A.",
      "Engaging the audience through clear and concise verbal communication, supplemented with visual aids if necessary.",
      "Addressing conflicts directly and calmly discussing potential solutions with involved parties.",
    ],
    selectedOption: null,
    selectedOrder: [
      "Holding a company-wide town hall meeting for interactive discussion and Q&A.",
      "Engaging the audience through clear and concise verbal communication, supplemented with visual aids if necessary.",
      "Addressing conflicts directly and calmly discussing potential solutions with involved parties.",
    ],
    saveText: "Save Order",
    section: 1,
    mostLikely: "",
    leastLikely: "",
  },
  {
    questionnaireNo: 26,
    question:
      "A friend confides in you about a mistake they made. How do you respond?",
    question_category: "default",
    questionOptionType: "RATING",
    questionWeightageType: "Rating",
    optionsList: [
      "Actively seeking out their input by asking direct questions and creating a supportive environment where all voices are valued.",
      "Communicating openly with team members to set realistic deadlines and regularly check in on progress.",
      "Approaching conflicts constructively by listening to all perspectives, finding common ground, and working towards a resolution.",
    ],
    selectedOption: null,
    selectedOrder: [
      "Actively seeking out their input by asking direct questions and creating a supportive environment where all voices are valued.",
      "Communicating openly with team members to set realistic deadlines and regularly check in on progress.",
      "Approaching conflicts constructively by listening to all perspectives, finding common ground, and working towards a resolution.",
    ],
    saveText: "Save Order",
    section: 1,
    mostLikely: "",
    leastLikely: "",
  },
  {
    questionnaireNo: 27,
    question:
      "You witness a stranger struggling with heavy bags. What do you do?",
    question_category: "default",
    questionOptionType: "RATING",
    questionWeightageType: "Rating",
    optionsList: [
      "Establishing clear channels of communication, providing regular updates, and encouraging open dialogue to address any issues that arise promptly.",
      "Acknowledging and appreciating each team member's contributions, actively listening to their ideas, and creating a supportive atmosphere where everyone feels heard.",
      "By actively listening to all parties involved and facilitating open communication to find a mutually beneficial solution.",
    ],
    selectedOption: null,
    selectedOrder: [
      "Establishing clear channels of communication, providing regular updates, and encouraging open dialogue to address any issues that arise promptly.",
      "Acknowledging and appreciating each team member's contributions, actively listening to their ideas, and creating a supportive atmosphere where everyone feels heard.",
      "By actively listening to all parties involved and facilitating open communication to find a mutually beneficial solution.",
    ],
    saveText: "Save Order",
    section: 1,
    mostLikely: "",
    leastLikely: "",
  },
  {
    questionnaireNo: 28,
    question:
      "How do you typically respond when someone shares good news with you?",
    question_category: "default",
    questionOptionType: "RATING",
    questionWeightageType: "Rating",
    optionsList: [
      "Striving to find common ground and encourage compromise to reach a resolution that satisfies everyone involved.",
      "Proactively seeking clarification from all parties involved and working towards clarifying any misconceptions to prevent escalation.",
      "Encouraging empathy and perspective-taking, helping each party understand the other's point of view to facilitate compromise.",
    ],
    selectedOption: null,
    selectedOrder: [
      "Striving to find common ground and encourage compromise to reach a resolution that satisfies everyone involved.",
      "Proactively seeking clarification from all parties involved and working towards clarifying any misconceptions to prevent escalation.",
      "Encouraging empathy and perspective-taking, helping each party understand the other's point of view to facilitate compromise.",
    ],
    saveText: "Save Order",
    section: 1,
    mostLikely: "",
    leastLikely: "",
  },
];
