export const Dummy_Benifits = [
  {
    name: "John paul ",
    status: "Actively Looking",
    email: "abc@test.com",
    openJobs: 5,
  },
  {
    name: "Niesh Kartalsd ",
    status: "Open for work",
    email: "abc@test.com",
    openJobs: 8,
  },
  {
    name: "candidate plan ",
    status: "Not looking for job",
    email: "abc@test.com",
    openJobs: 53,
  },
  {
    name: "Snajeev  ",
    status: "Actively Looking",
    email: "abc@test.com",
    openJobs: 4,
  },
  {
    name: "Gautam ",
    status: "Actively Looking",
    email: "abc@test.com",
    openJobs: 54,
  },
  {
    name: "Karip Plan ",
    status: "Actively Looking",
    email: "abc@test.com",
    openJobs: 6,
  },
  {
    name: "Trunjan ",
    status: "Open for work",
    email: "abc@test.com",
    openJobs: 5,
  },
  {
    name: "Vision plan",
    status: "Actively Looking",
    email: "abc@test.com",
    openJobs: 5,
  },
  {
    name: "Short Term",
    status: "Not looking for job",
    email: "abc@test.com",
    openJobs: 35,
  },
  {
    name: "Long Term",
    status: "Not looking for job",
    email: "abc@test.com",
    openJobs: 42,
  },
  {
    name: "Vision plan",
    status: "Actively Looking",
    email: "abc@test.com",
    openJobs: 52,
  },
  {
    name: "Education name",
    status: "Open for work",
    email: "abc@test.com",
    openJobs: 13,
  },
  {
    name: "401k name",
    status: "Actively Looking",
    email: "abc@test.com",
    openJobs: 18,
  },
  {
    name: "Child & Family Care",
    status: "Not looking for job",
    email: "abc@test.com",
    openJobs: 9,
  },
  {
    name: "401k name",
    status: "Not looking for job",
    email: "abc@test.com",
    openJobs: 17,
  },
  {
    name: "Commuter Benefits ",
    status: "Open for work",
    email: "abc@test.com",
    openJobs: 67,
  },
  {
    name: "Dental ",
    status: "Open for work",
    email: "abc@test.com",
    openJobs: 11,
  },
  {
    name: "Commuter Benefits ",
    status: "Actively Looking",
    email: "abc@test.com",
    openJobs: 13,
  },
];
